import 'package:flutter/material.dart';

enum FantasyLanguage { fr, en, ar }

class AppLanguageProvider extends ChangeNotifier {
  FantasyLanguage _language = FantasyLanguage.fr;

  FantasyLanguage get language => _language;

  Locale get locale => Locale(_language.name);

  TextDirection get textDirection =>
      _language == FantasyLanguage.ar ? TextDirection.rtl : TextDirection.ltr;

  bool get isArabic => _language == FantasyLanguage.ar;

  void setLanguage(FantasyLanguage language) {
    if (_language == language) return;
    _language = language;
    notifyListeners();
  }
}

extension AppText on BuildContext {
  String t(String key) {
    final inherited =
        dependOnInheritedWidgetOfExactType<_AppLanguageInherited>();
    final language = inherited?.language ?? FantasyLanguage.fr;
    return _translations[language]?[key] ??
        _translations[FantasyLanguage.fr]?[key] ??
        key;
  }
}

class AppLanguageScope extends StatelessWidget {
  final FantasyLanguage language;
  final TextDirection textDirection;
  final Widget child;

  const AppLanguageScope({
    super.key,
    required this.language,
    required this.textDirection,
    required this.child,
  });

  @override
  Widget build(BuildContext context) {
    return _AppLanguageInherited(
      language: language,
      child: Directionality(textDirection: textDirection, child: child),
    );
  }
}

class _AppLanguageInherited extends InheritedWidget {
  final FantasyLanguage language;

  const _AppLanguageInherited({required this.language, required super.child});

  @override
  bool updateShouldNotify(_AppLanguageInherited oldWidget) {
    return oldWidget.language != language;
  }
}

const Map<FantasyLanguage, Map<String, String>> _translations = {
  FantasyLanguage.fr: {
    'appName': 'Futivo',
    'splashTagline': 'Sport Fantasy Network',
    'news': 'News',
    'fantasy': 'Fantasy',
    'stats': 'Stats',
    'matches': 'Matchs',
    'standings': 'Classement',
    'myTeam': 'Mon équipe',
    'groups': 'Groupes',
    'market': 'Marché',
    'profile': 'Profil',
    'table': 'Tableau',
    'login': 'Connexion',
    'logout': 'Déconnexion',
    'createAccount': 'Créer un compte',
    'welcomeBack': 'Bon retour',
    'loginSubtitle': 'Connecte-toi avec ton téléphone ou pseudo.',
    'phoneOrNickname': 'Téléphone ou pseudo',
    'password': 'Mot de passe',
    'newToFantasy': 'Nouveau sur Futivo ?',
    'enterLogin': 'Saisis ton téléphone ou pseudo',
    'enterPassword': 'Saisis ton mot de passe',
    'noAccount': 'Aucun compte trouvé',
    'wrongPassword': 'Mot de passe incorrect',
    'loginFailed': 'Connexion échouée. Réessaie.',
    'registerTitle': 'Créer un compte',
    'registerSubtitle': 'Crée ton profil fantasy.',
    'fullName': 'Nom complet',
    'nickname': 'Pseudo',
    'phoneNumber': 'Téléphone',
    'confirmPassword': 'Confirmer le mot de passe',
    'nicknameAvailable': 'Pseudo disponible',
    'continue': 'Continuer',
    'chooseClub': 'Choisis ton équipe nationale',
    'chooseClubSubtitle':
        'Ton équipe nationale favorite personnalise ton profil et le mode Fantasy.',
    'couldNotSaveTeam': 'Impossible d’enregistrer le club. Réessaie.',
    'getStarted': 'Entrer sur Futivo',
    'heroBadge': 'FUTIVO SPORT FANTASY',
    'heroTitle': 'Futivo\nSport Fantasy',
    'heroSubtitle':
        'Actualités football, matchs Coupe du Monde 2026, classements et fantasy.',
    'heroFooter': 'News - Matchs - Marché fantasy - Groupes privés',
    'refresh': 'Actualiser',
    'waitRefresh': 'Attends {seconds}s avant d’actualiser.',
    'upcoming': 'À VENIR',
    'matchDetails': 'Détails du match',
    'worldCupMatches': 'Matchs Coupe du Monde 2026',
    'openingMatch': 'MATCH D OUVERTURE',
    'group': 'Groupe',
    'overview': 'Resume',
    'lineups': 'Compositions',
    'matchInformation': 'Informations du match',
    'venue': 'Stade',
    'kickoff': 'Coup d envoi',
    'matchId': 'ID match',
    'manualDataStatus': 'Donnees manuelles',
    'available': 'Disponible',
    'pending': 'En attente',
    'manualDataUnavailable': 'Donnees indisponibles',
    'manualDataUnavailableMessage':
        'Le backend ne repond pas encore pour les donnees manuelles de ce match.',
    'lineupsPending': 'Compositions en attente',
    'lineupsPendingMessage':
        'Ajoute plus tard le XI, la formation et les remplacants depuis le panneau admin.',
    'eventsPending': 'Evenements en attente',
    'eventsPendingMessage':
        'Ajoute les buts, cartons et penalties depuis le panneau admin ou une source gratuite.',
    'substitute': 'Remplacant',
    'goal': 'But',
    'yellowCard': 'Carton jaune',
    'redCard': 'Carton rouge',
    'penaltyScored': 'Penalty marque',
    'penaltyMissed': 'Penalty rate',
    'events': 'Événements',
    'couldNotLoadEvents': 'Impossible de charger les événements',
    'noEventsYet': 'Aucun événement',
    'eventsMessage':
        'Buts, cartons, remplacements et passes décisives apparaîtront ici.',
    'assist': 'Passe',
    'favoriteTeam': 'Équipe nationale favorite',
    'changeLater': 'Changer plus tard',
    'settings': 'Paramètres',
    'language': 'Langue',
    'languageSubtitle': 'Français / English / العربية',
    'newsroomTitle': 'Salle de presse Futivo',
    'newsroomSubtitle': 'Actualité Coupe du Monde, rapide et visuelle.',
    'newsAll': 'Toutes les news',
    'newsSearchResults': 'Résultats de recherche',
    'featuredNews': 'À LA UNE',
    'teams': 'Équipes',
    'hosts': 'Pays hôtes',
    'newsSearchHint': 'Rechercher par équipe, joueur, groupe ou mot-clé',
    'articlesCount': 'ARTICLES',
    'sponsored': 'SPONSORISE',
    'noArticlesFound': 'Aucun article trouvé',
    'tryAnotherNewsSearch':
        'Essaie une autre équipe, joueur, groupe ou mot-clé.',
    'newsDetailFooter': 'Actualité sportive via Futivo',
    'profileGuestTitle': 'Invité Futivo',
    'profileGuestSubtitle':
        'News, matchs et classements sont ouverts. Connecte-toi seulement pour Fantasy.',
    'profileStatus': 'Statut',
    'profileStatusActive': 'Compte actif',
    'profileMode': 'Mode',
    'profileModeWorldCup': 'Coupe du Monde 2026',
    'profileAccount': 'Compte',
    'profilePreferences': 'Préférences',
    'profileSecurity': 'Sécurité',
    'live': 'LIVE',
    'fantasyManager': 'Manager Fantasy',
    'fantasyControlCenter': 'Centre Fantasy Futivo',
    'fantasyControlSubtitle':
        'Effectif, groupes et marche dans un espace clair.',
    'fantasyAccountRequired': 'Compte Fantasy requis',
    'fantasyAccountRequiredSubtitle':
        'Les news, matchs et classements restent ouverts. Connecte-toi seulement pour creer ton equipe, rejoindre des groupes ou utiliser le marche.',
    'noEmail': 'Aucun email',
    'createGroup': 'Créer un groupe',
    'joinGroup': 'Rejoindre',
    'groupName': 'Nom du groupe',
    'enterGroupId': 'ID du groupe',
    'cancel': 'Annuler',
    'create': 'Créer',
    'join': 'Rejoindre',
    'yourGroups': 'Tes groupes',
    'noGroups': 'Aucun groupe. Crée ou rejoins un groupe.',
    'weeklyTop': 'Top national de la semaine',
    'noLeaderboard': 'Aucun classement réel pour le moment.',
    'competeFriends': 'Défie tes amis',
    'groupsSubtitle':
        'Crée un groupe, partage son ID et joue avec jusqu’à 7 amis.',
    'groupCreated': 'Groupe créé. ID à partager: {id}',
    'groupNotFound': 'ID de groupe introuvable',
    'groupFull': 'Ce groupe est plein. Maximum 7 membres.',
    'groupJoined': 'Groupe rejoint',
    'membersLeader': '{members}/7 membres • Leader: {leader}',
    'marketOpen': 'Marché ouvert',
    'marketClosed': 'Marché fermé',
    'marketOpenSubtitle': 'Recrute jusqu’à 16 joueurs avant la deadline.',
    'marketClosedSubtitle': 'Les transferts sont bloqués pour le moment.',
    'players': 'Joueurs',
    'budget': 'Budget',
    'squadRules': 'Règles d’équipe',
    'squadRulesSubtitle':
        'Construis une équipe de 16 joueurs: 2 GK, 5 DEF, 5 MID, 4 FWD.',
    'cannotAdd': 'Tu ne peux pas ajouter ce joueur.',
    'playerAdded': '{player} ajouté à ton équipe',
    'playerRemoved': '{player} retiré de ton équipe',
    'alreadySelected': 'Ce joueur est déjà dans ton équipe.',
    'squadFull': 'Ton équipe est complète. Maximum 16 joueurs.',
    'notEnoughBudget': 'Budget insuffisant.',
    'maxPosition': 'Tu as déjà sélectionné le maximum de joueurs {position}.',
    'myFantasySquad': 'Mon effectif Fantasy',
    'startingXi': 'Onze titulaire',
    'substitutes': 'Remplaçants',
    'empty': 'VIDE',
    'slot': 'Place',
    'noSubstitutes': 'Aucun remplaçant. Ajoute des joueurs depuis le Marché.',
    'remainingBudget': '{budget}M DZ restants',
    'usedBudget': '{budget}M / 100M DZ utilisés',
    'fantasyPointsRound': 'Points Fantasy - Tour {round}',
    'realDataPending': 'Donnees reelles en attente',
    'overall': 'Total',
    'thisRound': 'Ce tour',
    'syncRealPoints': 'Synchroniser les points',
    'scoringInfo':
        'Les points resteront vides jusqu a la connexion de l API de statistiques joueurs ou de la saisie admin.',
    'best': 'Meilleur',
    'previousWeeklyScores': 'Scores hebdomadaires precedents',
    'currentRoundPlayerPoints': 'Points joueurs du tour',
    'noPointsEvent': 'Aucun evenement de points',
    'captainRoles': 'Capitaines',
    'dragHint':
        'Appuie longuement et glisse un remplacant vers un poste compatible pour l entrer dans le onze.',
    'price': 'Prix',
    'points': 'Points',
    'status': 'Statut',
    'noPlayers': 'Aucun joueur',
    'changeFilterLater': 'Change le filtre ou reessaie plus tard.',
    'backendUnavailable': 'Backend indisponible. Demarre l API ASP.NET.',
    'backendStartHint': 'Demarre le backend puis actualise les groupes.',
    'members': 'membres',
    'openStatus': 'OUVERT',
    'fullStatus': 'PLEIN',
  },
  FantasyLanguage.en: {
    'appName': 'Futivo',
    'splashTagline': 'Sport Fantasy Network',
    'news': 'News',
    'fantasy': 'Fantasy',
    'stats': 'Stats',
    'matches': 'Matches',
    'standings': 'Standings',
    'myTeam': 'My team',
    'groups': 'Groups',
    'market': 'Market',
    'profile': 'Profile',
    'table': 'Table',
    'login': 'Login',
    'logout': 'Logout',
    'createAccount': 'Create account',
    'welcomeBack': 'Welcome back',
    'loginSubtitle': 'Login to play Fantasy mode.',
    'phoneOrNickname': 'Phone or nickname',
    'password': 'Password',
    'newToFantasy': 'New to Futivo?',
    'enterLogin': 'Enter your phone or nickname',
    'enterPassword': 'Enter your password',
    'noAccount': 'No account found',
    'wrongPassword': 'Wrong password',
    'loginFailed': 'Login failed. Try again.',
    'registerTitle': 'Create account',
    'registerSubtitle': 'Create your fantasy profile.',
    'fullName': 'Full name',
    'nickname': 'Nickname',
    'phoneNumber': 'Phone number',
    'confirmPassword': 'Confirm password',
    'nicknameAvailable': 'Nickname available',
    'continue': 'Continue',
    'chooseClub': 'Choose your national team',
    'chooseClubSubtitle':
        'Your favorite national team personalizes Fantasy and profile content.',
    'couldNotSaveTeam': 'Could not save the team. Try again.',
    'getStarted': 'Enter Futivo',
    'heroBadge': 'FUTIVO SPORT FANTASY',
    'heroTitle': 'Futivo\nSport Fantasy',
    'heroSubtitle':
        'Latest football news, World Cup 2026 matches, group standings and fantasy squads.',
    'heroFooter': 'News - Matches - Fantasy market - Private groups',
    'refresh': 'Refresh',
    'waitRefresh': 'Wait {seconds}s before refreshing.',
    'upcoming': 'Upcoming',
    'matchDetails': 'Match details',
    'worldCupMatches': 'World Cup 2026 matches',
    'openingMatch': 'Opening match',
    'group': 'Group',
    'overview': 'Overview',
    'lineups': 'Lineups',
    'matchInformation': 'Match information',
    'venue': 'Venue',
    'kickoff': 'Kickoff',
    'matchId': 'Match ID',
    'manualDataStatus': 'Manual data',
    'available': 'Available',
    'pending': 'Pending',
    'manualDataUnavailable': 'Data unavailable',
    'manualDataUnavailableMessage':
        'The backend is not responding yet for this match manual data.',
    'lineupsPending': 'Lineups pending',
    'lineupsPendingMessage':
        'Later you can add the XI, formation and substitutes from the admin panel.',
    'eventsPending': 'Events pending',
    'eventsPendingMessage':
        'Add goals, cards and penalties from the admin panel or a free source.',
    'substitute': 'Substitute',
    'goal': 'Goal',
    'yellowCard': 'Yellow card',
    'redCard': 'Red card',
    'penaltyScored': 'Penalty scored',
    'penaltyMissed': 'Penalty missed',
    'events': 'Events',
    'couldNotLoadEvents': 'Could not load events',
    'noEventsYet': 'No events yet',
    'eventsMessage': 'Goals, cards, substitutions and assists appear here.',
    'assist': 'Assist',
    'favoriteTeam': 'Favorite national team',
    'changeLater': 'Change later',
    'settings': 'Settings',
    'language': 'Language',
    'languageSubtitle': 'Français / English / العربية',
    'newsroomTitle': 'Futivo Newsroom',
    'newsroomSubtitle': 'World Cup intelligence, fast and visual.',
    'newsAll': 'All news',
    'newsSearchResults': 'Search results',
    'featuredNews': 'FEATURED',
    'teams': 'Teams',
    'hosts': 'Hosts',
    'newsSearchHint': 'Search news by team, player, group or keyword',
    'articlesCount': 'ARTICLES',
    'sponsored': 'SPONSORED',
    'noArticlesFound': 'No articles found',
    'tryAnotherNewsSearch': 'Try another team, player, group or keyword.',
    'newsDetailFooter': 'Sports coverage powered by Futivo',
    'profileGuestTitle': 'Futivo guest',
    'profileGuestSubtitle':
        'News, matches and standings are open. Login only for Fantasy.',
    'profileStatus': 'Status',
    'profileStatusActive': 'Active account',
    'profileMode': 'Mode',
    'profileModeWorldCup': 'World Cup 2026',
    'profileAccount': 'Account',
    'profilePreferences': 'Preferences',
    'profileSecurity': 'Security',
    'live': 'LIVE',
    'fantasyManager': 'Fantasy manager',
    'fantasyControlCenter': 'Futivo Fantasy Control',
    'fantasyControlSubtitle': 'Squad, groups and market in one clean space.',
    'fantasyAccountRequired': 'Fantasy account required',
    'fantasyAccountRequiredSubtitle':
        'News, matches and standings stay open. Login only to create your squad, join groups or use the market.',
    'noEmail': 'Guest account',
    'createGroup': 'Create group',
    'joinGroup': 'Join group',
    'groupName': 'Group name',
    'enterGroupId': 'Group ID',
    'cancel': 'Cancel',
    'create': 'Create',
    'join': 'Join',
    'yourGroups': 'Your groups',
    'noGroups': 'No group yet. Create or join one.',
    'weeklyTop': 'Weekly top',
    'noLeaderboard': 'No leaderboard yet.',
    'competeFriends': 'Compete with friends',
    'groupsSubtitle': 'Create a group, share its ID and play with friends.',
    'groupCreated': 'Group created. Share ID: {id}',
    'groupNotFound': 'Group ID not found',
    'groupFull': 'This group is full.',
    'groupJoined': 'Group joined',
    'membersLeader': '{members}/7 members - Leader: {leader}',
    'marketOpen': 'Market open',
    'marketClosed': 'Market closed',
    'marketOpenSubtitle': 'Recruit up to 16 players before the deadline.',
    'marketClosedSubtitle': 'Transfers are locked now.',
    'players': 'Players',
    'budget': 'Budget',
    'squadRules': 'Squad rules',
    'squadRulesSubtitle': 'Build a 16-player squad: 2 GK, 5 DEF, 5 MID, 4 FWD.',
    'cannotAdd': 'You cannot add this player.',
    'playerAdded': '{player} added to your team',
    'playerRemoved': '{player} removed from your team',
    'alreadySelected': 'This player is already in your team.',
    'squadFull': 'Your squad is full. Maximum 16 players.',
    'notEnoughBudget': 'Not enough budget.',
    'maxPosition': 'You already selected the maximum {position} players.',
    'myFantasySquad': 'My fantasy squad',
    'startingXi': 'Starting XI',
    'substitutes': 'Substitutes',
    'empty': 'Empty',
    'slot': 'Slot',
    'noSubstitutes': 'No substitutes. Add players from the market.',
    'remainingBudget': '{budget}M remaining',
    'usedBudget': '{budget}M / 100M used',
    'fantasyPointsRound': 'Fantasy points - Round {round}',
    'realDataPending': 'Real data pending',
    'overall': 'Overall',
    'thisRound': 'This round',
    'syncRealPoints': 'Sync real points',
    'scoringInfo':
        'Points stay empty until a player statistics API or admin stats are connected.',
    'best': 'Best',
    'previousWeeklyScores': 'Previous weekly scores',
    'currentRoundPlayerPoints': 'Current round player points',
    'noPointsEvent': 'No points event',
    'captainRoles': 'Captain roles',
    'dragHint':
        'Long press and drag a bench player onto a matching pitch position to swap him into the XI.',
    'price': 'Price',
    'points': 'Points',
    'status': 'Status',
    'noPlayers': 'No players',
    'changeFilterLater': 'Change the filter or try again later.',
    'backendUnavailable': 'Backend unavailable. Start the ASP.NET API.',
    'backendStartHint': 'Start the backend, then refresh your groups.',
    'members': 'members',
    'openStatus': 'OPEN',
    'fullStatus': 'FULL',
  },
  FantasyLanguage.ar: {
    'appName': 'Futivo',
    'splashTagline': 'منصة فانتازي كرة القدم',
    'news': 'الأخبار',
    'fantasy': 'فانتازي',
    'stats': 'الإحصائيات',
    'matches': 'المباريات',
    'standings': 'الترتيب',
    'myTeam': 'فريقي',
    'groups': 'المجموعات',
    'market': 'السوق',
    'profile': 'الملف',
    'table': 'الترتيب',
    'login': 'دخول',
    'logout': 'تسجيل الخروج',
    'createAccount': 'إنشاء حساب',
    'welcomeBack': 'مرحبا بعودتك',
    'loginSubtitle': 'ادخل برقم الهاتف أو الاسم.',
    'phoneOrNickname': 'الهاتف أو الاسم',
    'password': 'كلمة المرور',
    'newToFantasy': 'جديد في فانتازي DZ؟',
    'enterLogin': 'أدخل الهاتف أو الاسم',
    'enterPassword': 'أدخل كلمة المرور',
    'noAccount': 'لا يوجد حساب بهذه البيانات',
    'wrongPassword': 'كلمة المرور خاطئة',
    'loginFailed': 'فشل الدخول. حاول مرة أخرى.',
    'registerTitle': 'إنشاء حساب',
    'registerSubtitle': 'أنشئ ملفك وابدأ فانتازي DZ.',
    'fullName': 'الاسم الكامل',
    'nickname': 'الاسم',
    'phoneNumber': 'رقم الهاتف',
    'confirmPassword': 'تأكيد كلمة المرور',
    'nicknameAvailable': 'الاسم متاح',
    'continue': 'متابعة',
    'chooseClub': 'اختر ناديك',
    'chooseClubSubtitle': 'ناديك المفضل يخصص المباريات والترتيب والملخصات.',
    'couldNotSaveTeam': 'تعذر حفظ النادي. حاول مرة أخرى.',
    'getStarted': 'ابدأ',
    'heroBadge': 'فانتازي كرة القدم الجزائرية',
    'heroTitle': 'ابن\nفريق أحلامك',
    'heroSubtitle': 'اختر اللاعبين، نافس أصدقاءك، وسيطر على دوري فانتازي DZ.',
    'heroFooter': 'مباريات مباشرة • نقاط فانتازي • دوريات الأصدقاء',
    'refresh': 'تحديث',
    'waitRefresh': 'انتظر {seconds}ث قبل التحديث.',
    'upcoming': 'قادمة',
    'matchDetails': 'تفاصيل المباراة',
    'worldCupMatches': 'مباريات كأس العالم 2026',
    'openingMatch': 'مباراة الافتتاح',
    'group': 'المجموعة',
    'overview': 'نظرة عامة',
    'lineups': 'التشكيلات',
    'matchInformation': 'معلومات المباراة',
    'venue': 'الملعب',
    'kickoff': 'وقت البداية',
    'matchId': 'معرف المباراة',
    'manualDataStatus': 'البيانات اليدوية',
    'available': 'متوفر',
    'pending': 'قيد الانتظار',
    'manualDataUnavailable': 'البيانات غير متوفرة',
    'manualDataUnavailableMessage':
        'الخادم لا يرد حاليا على بيانات هذه المباراة اليدوية.',
    'lineupsPending': 'التشكيلات قيد الانتظار',
    'lineupsPendingMessage':
        'يمكنك لاحقا إضافة التشكيلة والخطة والبدلاء من لوحة الإدارة.',
    'eventsPending': 'الأحداث قيد الانتظار',
    'eventsPendingMessage':
        'أضف الأهداف والبطاقات وركلات الجزاء من لوحة الإدارة أو مصدر مجاني.',
    'substitute': 'بديل',
    'goal': 'هدف',
    'yellowCard': 'بطاقة صفراء',
    'redCard': 'بطاقة حمراء',
    'penaltyScored': 'ركلة جزاء مسجلة',
    'penaltyMissed': 'ركلة جزاء ضائعة',
    'events': 'الأحداث',
    'couldNotLoadEvents': 'تعذر تحميل الأحداث',
    'noEventsYet': 'لا توجد أحداث',
    'eventsMessage':
        'الأهداف، البطاقات، التبديلات والتمريرات الحاسمة تظهر هنا.',
    'assist': 'تمريرة',
    'favoriteTeam': 'النادي المفضل',
    'changeLater': 'تغيير لاحقا',
    'settings': 'الإعدادات',
    'language': 'اللغة',
    'languageSubtitle': 'Français / العربية',
    'newsroomTitle': 'غرفة أخبار Futivo',
    'newsroomSubtitle': 'أخبار كأس العالم بسرعة وبصور واضحة.',
    'newsAll': 'كل الأخبار',
    'newsSearchResults': 'نتائج البحث',
    'featuredNews': 'الأبرز',
    'teams': 'المنتخبات',
    'hosts': 'المضيفون',
    'newsSearchHint': 'ابحث باسم منتخب، لاعب، مجموعة أو كلمة',
    'articlesCount': 'مقالات',
    'sponsored': 'إعلان',
    'noArticlesFound': 'لا توجد مقالات',
    'tryAnotherNewsSearch': 'جرّب منتخبًا أو لاعبًا أو كلمة أخرى.',
    'newsDetailFooter': 'تغطية رياضية عبر Futivo',
    'profileGuestTitle': 'زائر Futivo',
    'profileGuestSubtitle':
        'الأخبار والمباريات والترتيب مفتوحة. سجّل الدخول فقط للفانتازي.',
    'profileStatus': 'الحالة',
    'profileStatusActive': 'حساب نشط',
    'profileMode': 'الوضع',
    'profileModeWorldCup': 'كأس العالم 2026',
    'profileAccount': 'الحساب',
    'profilePreferences': 'التفضيلات',
    'profileSecurity': 'الأمان',
    'live': 'مباشر',
    'fantasyManager': 'مدرب فانتازي',
    'fantasyControlCenter': 'مركز فانتازي Futivo',
    'fantasyControlSubtitle': 'فريقك والمجموعات والسوق في مساحة واحدة.',
    'fantasyAccountRequired': 'حساب فانتازي مطلوب',
    'fantasyAccountRequiredSubtitle':
        'الأخبار والمباريات والترتيب متاحة للجميع. سجل الدخول فقط لإنشاء فريقك أو دخول المجموعات أو استخدام السوق.',
    'noEmail': 'لا يوجد بريد',
    'createGroup': 'إنشاء مجموعة',
    'joinGroup': 'انضمام',
    'groupName': 'اسم المجموعة',
    'enterGroupId': 'أدخل ID المجموعة',
    'cancel': 'إلغاء',
    'create': 'إنشاء',
    'join': 'انضمام',
    'yourGroups': 'مجموعاتك',
    'noGroups': 'لا توجد مجموعات. أنشئ أو انضم لمجموعة.',
    'weeklyTop': 'أفضل 3 وطنيا هذا الأسبوع',
    'noLeaderboard': 'لا يوجد ترتيب حقيقي حاليا.',
    'competeFriends': 'نافس أصدقاءك',
    'groupsSubtitle': 'أنشئ مجموعة، شارك ID، والعب مع 7 أصدقاء.',
    'groupCreated': 'تم إنشاء المجموعة. ID: {id}',
    'groupNotFound': 'ID المجموعة غير موجود',
    'groupFull': 'هذه المجموعة ممتلئة. الحد 7 أعضاء.',
    'groupJoined': 'تم الانضمام للمجموعة',
    'membersLeader': '{members}/7 أعضاء • القائد: {leader}',
    'marketOpen': 'السوق مفتوح',
    'marketClosed': 'السوق مغلق',
    'marketOpenSubtitle': 'اختر حتى 16 لاعبا قبل نهاية المهلة.',
    'marketClosedSubtitle': 'التحويلات مغلقة حاليا.',
    'players': 'لاعبون',
    'budget': 'الميزانية',
    'squadRules': 'قواعد الفريق',
    'squadRulesSubtitle': 'ابن فريقا من 16 لاعبا: 2 GK، 5 DEF، 5 MID، 4 FWD.',
    'cannotAdd': 'لا يمكنك إضافة هذا اللاعب.',
    'playerAdded': 'تمت إضافة {player} إلى فريقك',
    'playerRemoved': 'تم حذف {player} من فريقك',
    'alreadySelected': 'هذا اللاعب موجود في فريقك.',
    'squadFull': 'فريقك مكتمل. الحد 16 لاعبا.',
    'notEnoughBudget': 'الميزانية غير كافية.',
    'maxPosition': 'اخترت الحد الأقصى من لاعبي {position}.',
    'myFantasySquad': 'تشكيلتي الفانتازي',
    'startingXi': 'التشكيلة الأساسية',
    'substitutes': 'البدلاء',
    'empty': 'فارغ',
    'slot': 'مكان',
    'noSubstitutes': 'لا يوجد بدلاء. أضف لاعبين من السوق.',
    'remainingBudget': 'متبقي {budget}M DZ',
    'usedBudget': 'مستعمل {budget}M / 100M DZ',
    'fantasyPointsRound': 'نقاط الفانتازي - الجولة {round}',
    'realDataPending': 'البيانات الحقيقية قيد الانتظار',
    'overall': 'المجموع',
    'thisRound': 'هذه الجولة',
    'syncRealPoints': 'مزامنة النقاط',
    'scoringInfo':
        'تبقى النقاط فارغة حتى يتم ربط API إحصائيات اللاعبين أو إدخالها من لوحة الإدارة.',
    'best': 'الأفضل',
    'previousWeeklyScores': 'نتائج الأسابيع السابقة',
    'currentRoundPlayerPoints': 'نقاط لاعبي الجولة',
    'noPointsEvent': 'لا توجد أحداث نقاط',
    'captainRoles': 'الأدوار القيادية',
    'dragHint':
        'اضغط مطولا واسحب لاعبا احتياطيا إلى مركز مناسب لإدخاله في التشكيلة.',
    'price': 'السعر',
    'points': 'النقاط',
    'status': 'الحالة',
    'noPlayers': 'لا يوجد لاعبون',
    'changeFilterLater': 'غير الفلتر أو حاول لاحقا.',
    'backendUnavailable': 'الخادم غير متاح. شغل API الخاص ب ASP.NET.',
    'backendStartHint': 'شغل الخادم ثم حدث المجموعات.',
    'members': 'أعضاء',
    'openStatus': 'مفتوح',
    'fullStatus': 'ممتلئ',
  },
};

String trReplace(String text, Map<String, String> values) {
  var result = text;
  for (final entry in values.entries) {
    result = result.replaceAll('{${entry.key}}', entry.value);
  }
  return result;
}
